# Generated by Django 5.1.3 on 2025-03-30 00:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Autor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("bio", models.TextField(blank=True)),
                (
                    "foto",
                    models.ImageField(
                        blank=True, null=True, upload_to="autores_fotos/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Artigo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("conteudo", models.TextField()),
                (
                    "data_publicacao",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "imagem_capa",
                    models.ImageField(
                        blank=True, null=True, upload_to="capas_artigos/"
                    ),
                ),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artigos",
                        to="autores.autor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comentario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_comentador", models.CharField(max_length=100)),
                ("texto", models.TextField()),
                ("data", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "artigo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comentarios",
                        to="autores.artigo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor", models.IntegerField()),
                ("data", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "artigo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="autores.artigo",
                    ),
                ),
            ],
        ),
    ]
