# Generated by Django 5.1.3 on 2025-04-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bandas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="banda",
            name="nacionalidade",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
